language: python   

python:
  - "2.7" 

install:
   - sudo apt-get install libmysqlclient-dev
   - sudo apt-get install python-dev
   - pip install --upgrade pip
   - pip install MySQL-python
   - pip install Flask
   - pip install nose  

script:       # script para tests
   - nosetests -with-coverage --cover-package=chip8 test
   - nosetests -with-coverage --cover-package=chip8 ./test/test.py
