language: python   

python:
  - "2.7" 

install:   # Instalación de dependencias
#  - sudo apt-get install libmysqlclient-dev
#  - sudo apt-get install python-dev
  - pip install --upgrade pip
  - pip install MySQL-python
  - pip install Flask
  - pip install nose  

script:       # script para tests
#  - nosetests

